# Ex1: 5x3 matrix for the value of x

In [1]:
x <- 1:15
x

matrix(x, nrow = 5, ncol = 3)

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

[,1] [,2] [,3]
[1,] 1     6   11  
[2,] 2     7   12  
[3,] 3     8   13  
[4,] 4     9   14  
[5,] 5    10   15

# Ex2: 4x4 matrix

In [2]:
matrix(0, nrow = 4, ncol = 4)

[,1] [,2] [,3] [,4]
[1,] 0    0    0    0   
[2,] 0    0    0    0   
[3,] 0    0    0    0   
[4,] 0    0    0    0

# Ex3: Generate 3x8 matrix


In [3]:
x <- 1:8
y <- rev(x)
z <- rep(3, each=8)
x
y
z

rbind(x,y,z)

[1] 1 2 3 4 5 6 7 8

[1] 8 7 6 5 4 3 2 1

[1] 3 3 3 3 3 3 3 3

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
x 1    2    3    4    5    6    7    8   
y 8    7    6    5    4    3    2    1   
z 3    3    3    3    3    3    3    3

# Ex4: 4x4 Matrix arithmetic operations

In [9]:
x <- matrix(1:16, nrow = 4, ncol = 4)
y <- matrix(17:32, nrow = 4, ncol = 4)


#(a). x + y
print('a')
a <- x + y
a

#(b). x - y 
print('b')
b <- x - y
b

#(c). x*y
print('c')
c <- x * y
c

#(d). x%*%y
print('d')
d <- x %*% y
d

#(e). Difference between (c) &(d) 
print('e')
e <- c - d
e

#(f). Inverse of y 
print('f')
#solve(y)
print("Inverse doesn't exist")


#(g). z<-x/y 
print('g')
z <- x / y
z



#(h). Transpose of z 
print('h')
h <- t(z)
h

#(i). Diagonal of transpose matrix 
print('i')
diagmatrix <- diag(h)
diagmatrix


[1] "a"


[,1] [,2] [,3] [,4]
[1,] 18   26   34   42  
[2,] 20   28   36   44  
[3,] 22   30   38   46  
[4,] 24   32   40   48

[1] "b"


[,1] [,2] [,3] [,4]
[1,] -16  -16  -16  -16 
[2,] -16  -16  -16  -16 
[3,] -16  -16  -16  -16 
[4,] -16  -16  -16  -16

[1] "c"


[,1] [,2] [,3] [,4]
[1,] 17   105  225  377 
[2,] 36   132  260  420 
[3,] 57   161  297  465 
[4,] 80   192  336  512

[1] "d"


[,1] [,2] [,3] [,4]
[1,] 538  650   762  874
[2,] 612  740   868  996
[3,] 686  830   974 1118
[4,] 760  920  1080 1240

[1] "e"


[,1] [,2] [,3] [,4]
[1,] -521 -545 -537 -497
[2,] -576 -608 -608 -576
[3,] -629 -669 -677 -653
[4,] -680 -728 -744 -728

[1] "f"
[1] "Inverse doesn't exist"
[1] "g"


[,1]       [,2]      [,3]      [,4]     
[1,] 0.05882353 0.2380952 0.3600000 0.4482759
[2,] 0.11111111 0.2727273 0.3846154 0.4666667
[3,] 0.15789474 0.3043478 0.4074074 0.4838710
[4,] 0.20000000 0.3333333 0.4285714 0.5000000

[1] "h"


[,1]       [,2]      [,3]      [,4]     
[1,] 0.05882353 0.1111111 0.1578947 0.2000000
[2,] 0.23809524 0.2727273 0.3043478 0.3333333
[3,] 0.36000000 0.3846154 0.4074074 0.4285714
[4,] 0.44827586 0.4666667 0.4838710 0.5000000

[1] "i"


[1] 0.05882353 0.27272727 0.40740741 0.50000000

# Ex5: Different between (i) & (ii)

In [10]:
xi<-matrix(x<-1:9,3,3,byrow = TRUE)
xii<-matrix(x<-1:9,3,3)
all.equal(xi,xii)
diff <- xi - xii
diff

[1] "Mean relative difference: 0.5333333"

[,1] [,2] [,3]
[1,] 0    -2   -4  
[2,] 2     0   -2  
[3,] 4     2    0

# Ex6: 
### Inner Product use A %*% B
### Outer Product use A %o% B

# Ex7:
all.equal(x,y) function is a utility to compare R objects x and y testing ‘near equality’. If they are any different, the comparison is still made to some extent, and a report of the differences is returned.

In [11]:
all.equal(xi,xii)

m1 <- matrix(1.0:9.0, nrow = 3)
m1
m2 <- matrix(1:9, nrow = 3)
m2

all.equal(m1,m2)

[1] "Mean relative difference: 0.5333333"

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] TRUE

# Ex8: Explain the use of dim() function with a sample program.

dim() function gets or sets the dimension of a matrix, array or data frame.

In [13]:
#set matrix dimension
x <- 1:12 ; dim(x) <- c(3,4)
x

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

# Ex9: Use of $ operator, and square brackets [] in List with example program. 

In [23]:
df <- data.frame(animal = c("apple", "orange", "banana"),
color = c("red", "orange", "yellow"), amount = c(1, 2, 3))
df[1]
df$color

animal
1 apple 
2 orange
3 banana

[1] red    orange yellow
Levels: orange red yellow

# Ex10: ifelse statement
Syntax: if (condition) {...} else {...}. && and || can be used in the condition. If else statement can be nested.

In [29]:
test <- c(1:10)
test 
print("Print out those sample numbers that are even using if else statement")
for (thistest in test)
{
 if (thistest %% 2 != 0) next
 else print(thistest)
}

[1]  1  2  3  4  5  6  7  8  9 10

[1] "Print out those sample numbers that are even using if else statement"
[1] 2
[1] 4
[1] 6
[1] 8
[1] 10


# Ex11: BMI Calculator

In [30]:
print("BMI Calc")
weight <- readline(prompt="Enter weight(kg): ")
weight <- as.numeric(weight)
height <- readline(prompt="Enter height(cm): ")
height <- as.numeric(height)
height <- height/100
BMI <- (weight/(height^2))
round(BMI, 1)

category <- ifelse(BMI >= 30, "obese", 
               ifelse(BMI >=25, "overweight", 
                  ifelse(BMI >=18.5, "normal", "underweight")))
category

[1] "BMI Calc"


Enter weight(kg):  74
Enter height(cm):  168


[1] 26.2

[1] "overweight"

# Ex12: List vs Data frames
- R list data type refers to an object consisting of an ordered collection of elements. The elements may be of different mode or type.
- R data.frame is a powerful data type, especially when processing table (.csv). It can store the data as row and columns according to the table. The difference between data frame and list is that the column data of data frame may be of different modes and attributes.




In [33]:
df1 <- data.frame(animal = c("apple", "orange", "banana"),
color = c("red", "orange", "yellow"), amount = c(1, 2, 3))
df1

l1 <- list(animal = c("apple", "orange", "banana"),
color = c("red", "orange", "yellow"), amount = c(1, 2, 3))
l1


animal color  amount
1 apple  red    1     
2 orange orange 2     
3 banana yellow 3

$animal
[1] "apple"  "orange" "banana"

$color
[1] "red"    "orange" "yellow"

$amount
[1] 1 2 3

# Ex13: repeat vs while loop
repeat is similar to while and for loop, it will execute a block of commands repeatly till break. Also similiar to do while loop

In [37]:
total <- 0
repeat { total <- total + 1; print(total); if (total > 6) break; }
total

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7


[1] 7

while() loop will execute a block of commands until the condition is no longer satisfied.

In [36]:
x <- 1
while(x < 5) {x <- x+1; if (x == 3) break; print(x); }

[1] 2
